DATABASE_HOST:
DATABASE_USERNAME:
DATABASE_PASSWORD:
DATABASE_NAME:

SECRET_KEY_BASE:

REDIS_URL:

GOOGLE_API_KEY:
GOOGLE_APPLICATION_CREDENTIALS:

ANSWERS_PATH:
BUTTONS_PATH:
FAQ_GIGA_PATH:
FAQ_INVEST_PATH:
FAQ_TRADER_PATH:
FAQ_OTHER_PATH:
