pagy:
  instances:
    vars: vars
  items_default: 30
  page_default: 1
epoch_time:
  day_in_secs: 86400
user:
  password:
    regexp: !ruby/regexp /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&])[a-zA-Z\d@$!%*#?&]{8,}\z/
    at_least: 8
